In [1]:
# Importing Dependencies
import pandas as pd
import numpy as np

In [2]:
# Uploading Original CSV files
csv1 = "JC-202203-citibike-tripdata.csv"
csv2 = "JC-202303-citibike-tripdata.csv"
citibike_data_2022 = pd.read_csv(csv1)
citibike_data_2023 = pd.read_csv(csv2)

In [4]:
citibike_data_2022.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,3255D3E3F33CDC45,classic_bike,2022-03-18 15:38:17,2022-03-18 15:45:34,Mama Johnson Field - 4 St & Jackson St,HB404,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,40.743140,-74.040041,40.736982,-74.027781,casual
1,17FA5604A37338F9,electric_bike,2022-03-04 16:44:48,2022-03-04 16:50:45,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member
2,7DEC9ADDB8D6BBE1,electric_bike,2022-03-13 17:44:32,2022-03-13 17:54:44,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member
3,9D69F74EEF231A2E,classic_bike,2022-03-13 15:33:47,2022-03-13 15:41:22,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member
4,C84AE4A9D78A6347,classic_bike,2022-03-11 12:21:18,2022-03-11 12:33:24,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member

In [5]:
citibike_data_2023.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,38F943EA06A4E54F,electric_bike,2023-03-25 09:20:57,2023-03-25 09:32:10,Jersey & 6th St,JC027,Glenwood Ave,JC094,40.725289,-74.045572,40.727551,-74.071061,member
1,C76EFC4C3B771E88,electric_bike,2023-03-15 07:55:41,2023-03-15 08:07:44,Jersey & 6th St,JC027,Glenwood Ave,JC094,40.725289,-74.045572,40.727551,-74.071061,casual
2,02C7BC83975952E6,electric_bike,2023-03-20 08:50:11,2023-03-20 09:00:37,Jersey & 6th St,JC027,Glenwood Ave,JC094,40.725289,-74.045572,40.727551,-74.071061,member
3,DB0FB572E0AA9C36,electric_bike,2023-03-02 10:17:07,2023-03-02 10:27:22,Jersey & 6th St,JC027,Glenwood Ave,JC094,40.725289,-74.045572,40.727551,-74.071061,casual
4,A238B2BDD1072D52,electric_bike,2023-03-04 09:13:23,2023-03-04 09:25:30,Jersey & 6th St,JC027,Glenwood Ave,JC094,40.725289,-74.045572,40.727551,-74.071061,member

In [8]:
# Cheking data types 2022
citibike_data_2022.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [10]:
# Cheking data types 2023
citibike_data_2022.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [12]:
merged_df = pd.concat([citibike_data_2022, citibike_data_2023], ignore_index=True)
merged_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,3255D3E3F33CDC45,classic_bike,2022-03-18 15:38:17,2022-03-18 15:45:34,Mama Johnson Field - 4 St & Jackson St,HB404,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,40.743140,-74.040041,40.736982,-74.027781,casual
1,17FA5604A37338F9,electric_bike,2022-03-04 16:44:48,2022-03-04 16:50:45,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member
2,7DEC9ADDB8D6BBE1,electric_bike,2022-03-13 17:44:32,2022-03-13 17:54:44,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member
3,9D69F74EEF231A2E,classic_bike,2022-03-13 15:33:47,2022-03-13 15:41:22,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member
4,C84AE4A9D78A6347,classic_bike,2022-03-11 12:21:18,2022-03-11 12:33:24,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member

In [16]:
# Convert the "started_at" and "ended_at" columns to pandas datetime objects
merged_df["started_at"] = pd.to_datetime(merged_df["started_at"])
merged_df["ended_at"] = pd.to_datetime(merged_df["ended_at"])

# Extract the date and time components into separate columns
merged_df["start_date"] = merged_df["started_at"].dt.date
merged_df["start_time"] = merged_df["started_at"].dt.time
merged_df["end_date"] = merged_df["ended_at"].dt.date
merged_df["end_time"] = merged_df["ended_at"].dt.time

# drop the original "started_at" and "ended_at" columns
merged_df.drop(columns=["started_at", "ended_at"], inplace=True)

In [17]:
merged_df

,ride_id,rideable_type,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,start_date,start_time,end_date,end_time
0,3255D3E3F33CDC45,classic_bike,Mama Johnson Field - 4 St & Jackson St,HB404,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,40.743140,-74.040041,40.736982,-74.027781,casual,2022-03-18,15:38:17,2022-03-18,15:45:34
1,17FA5604A37338F9,electric_bike,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-04,16:44:48,2022-03-04,16:50:45
2,7DEC9ADDB8D6BBE1,electric_bike,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-13,17:44:32,2022-03-13,17:54:44
3,9D69F74EEF231A2E,classic_bike,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-13,15:33:47,2022-03-13,15:41:22
4,C84AE4A9D78A6347,classic_bike,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-11,12:21:18,2022-03-11,12:33:24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114738,BF0032DA4A305161,classic_bike,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.738790,-74.039300,40.748161,-74.032453,member,2023-03-19,16:25:24,2023-03-19,16:33:20
114739,32172F9BEF8D56A2,classic_bike,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.738790,-74.039300,40.748161,-74.032453,casual,2023-03-22,16:14:15,2023-03-22,16:20:28
114740,6FCF0C7C1E254341,electric_bike,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.738790,-74.039300,40.748161,-74.032453,casual,2023-03-19,02:16:02,2023-03-19,02:21:15
114741,34DFBEB02424B55E,electric_bike,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.738790,-74.039300,40.748161,-74.032453,casual,2023-03-30,20:09:24,2023-03-30,20:15:08
114742,A235AD010540ACA2,classic_bike,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.738790,-74.039300,40.748161,-74.032453,casual,2023-03-17,17:53:28,2023-03-17,17:59:43

In [19]:
merged_df.dtypes

ride_id                object
rideable_type          object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
start_date             object
start_time             object
end_date               object
end_time               object
dtype: object

In [23]:
# Convert "start_date" and "end_date" to pandas datetime objects
merged_df["start_date"] = pd.to_datetime(merged_df["start_date"])
merged_df["end_date"] = pd.to_datetime(merged_df["end_date"])

# Convert "start_time" and "end_time" to pandas datetime objects with a specific format
merged_df["start_time"] = pd.to_datetime(merged_df["start_time"], format="%H:%M:%S").dt.time
merged_df["end_time"] = pd.to_datetime(merged_df["end_time"], format="%H:%M:%S").dt.time

In [24]:
# Verify new DataTypes
merged_df.dtypes

ride_id                       object
rideable_type                 object
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
start_date            datetime64[ns]
start_time                    object
end_date              datetime64[ns]
end_time                      object
dtype: object

In [25]:
merged_df

,ride_id,rideable_type,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,start_date,start_time,end_date,end_time
0,3255D3E3F33CDC45,classic_bike,Mama Johnson Field - 4 St & Jackson St,HB404,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,40.743140,-74.040041,40.736982,-74.027781,casual,2022-03-18,15:38:17,2022-03-18,15:45:34
1,17FA5604A37338F9,electric_bike,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-04,16:44:48,2022-03-04,16:50:45
2,7DEC9ADDB8D6BBE1,electric_bike,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-13,17:44:32,2022-03-13,17:54:44
3,9D69F74EEF231A2E,classic_bike,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-13,15:33:47,2022-03-13,15:41:22
4,C84AE4A9D78A6347,classic_bike,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-11,12:21:18,2022-03-11,12:33:24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114738,BF0032DA4A305161,classic_bike,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.738790,-74.039300,40.748161,-74.032453,member,2023-03-19,16:25:24,2023-03-19,16:33:20
114739,32172F9BEF8D56A2,classic_bike,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.738790,-74.039300,40.748161,-74.032453,casual,2023-03-22,16:14:15,2023-03-22,16:20:28
114740,6FCF0C7C1E254341,electric_bike,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.738790,-74.039300,40.748161,-74.032453,casual,2023-03-19,02:16:02,2023-03-19,02:21:15
114741,34DFBEB02424B55E,electric_bike,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.738790,-74.039300,40.748161,-74.032453,casual,2023-03-30,20:09:24,2023-03-30,20:15:08
114742,A235AD010540ACA2,classic_bike,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.738790,-74.039300,40.748161,-74.032453,casual,2023-03-17,17:53:28,2023-03-17,17:59:43

In [26]:
# Define the path where you want to save the CSV file
output_path = r'Z:\Private\drodriguez\Info\Info General DRDLVS\TEC Analytics Bootcamp\Module 18 Challenge\Data\cleaned_data.csv'

# Export the DataFrame to a CSV file
merged_df.to_csv(output_path, index=False)

print("DataFrame exported to CSV successfully.")

DataFrame exported to CSV successfully.